name: CI-NoAction
on:
  workflow_call:
    inputs:
      workspacename:
        required: true
        type: string
    secrets:
      clientid:
        required: true
      secret:
        required: true
      tenantid:
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Call the PS script and publish PBI contents
        shell: powershell
        run: |
          . GitHub/run-task.ps1 -ClientId ${{ secrets.clientid }} -Secret ${{ secrets.secret }} -TenantId ${{ secrets.tenantid }} -WorkspaceName ${{ inputs.workspacename }}
